export interface VocabWord {
  id: string;
  word: string;
  meaning: string;
  category: string;
}

export const CATEGORIES = [
  'Semua',
  'Pronouns',
  'Daily Verbs',
  'Adjectives',
  'Common Nouns',
  'People',
  'Places',
  'Objects',
  'School',
  'House',
  'Work',
  'Technology',
  'Transportation',
  'Food',
  'Nature',
  'Time',
  'Days',
  'Months',
  'Numbers',
  'Colors',
  'Family',
  'Weather',
  'Animals',
  'Food & Drinks',
  'Question Words',
  'Conjunctions',
  'Emotions',
  'Jobs',
  'Body',
  'Furniture',
  'Education',
  'Travel',
  'Shopping',
];

export const VOCABULARY: VocabWord[] = [
  // Pronouns
  { id: 'v-001', word: 'I', meaning: 'Saya / Aku', category: 'Pronouns' },
  { id: 'v-002', word: 'You', meaning: 'Kamu / Anda', category: 'Pronouns' },
  { id: 'v-003', word: 'He', meaning: 'Dia (laki-laki)', category: 'Pronouns' },
  { id: 'v-004', word: 'She', meaning: 'Dia (perempuan)', category: 'Pronouns' },
  { id: 'v-005', word: 'It', meaning: 'Itu (benda/hewan)', category: 'Pronouns' },
  { id: 'v-006', word: 'We', meaning: 'Kami / Kita', category: 'Pronouns' },
  { id: 'v-007', word: 'They', meaning: 'Mereka', category: 'Pronouns' },
  { id: 'v-008', word: 'Me', meaning: 'Saya (objek)', category: 'Pronouns' },
  { id: 'v-009', word: 'Him', meaning: 'Dia laki-laki (objek)', category: 'Pronouns' },
  { id: 'v-010', word: 'Her', meaning: 'Dia perempuan (objek)', category: 'Pronouns' },
  { id: 'v-011', word: 'Us', meaning: 'Kami (objek)', category: 'Pronouns' },
  { id: 'v-012', word: 'Them', meaning: 'Mereka (objek)', category: 'Pronouns' },
  { id: 'v-013', word: 'My', meaning: 'Milikku / Milik saya', category: 'Pronouns' },
  { id: 'v-014', word: 'Your', meaning: 'Milikmu / Milik kamu', category: 'Pronouns' },
  { id: 'v-015', word: 'His', meaning: 'Miliknya (laki-laki)', category: 'Pronouns' },
  { id: 'v-016', word: 'Their', meaning: 'Milik mereka', category: 'Pronouns' },
  { id: 'v-017', word: 'Our', meaning: 'Milik kami / kita', category: 'Pronouns' },
  { id: 'v-018', word: 'Myself', meaning: 'Diri saya sendiri', category: 'Pronouns' },
  { id: 'v-019', word: 'Yourself', meaning: 'Diri kamu sendiri', category: 'Pronouns' },
  { id: 'v-020', word: 'Himself', meaning: 'Dirinya sendiri (laki-laki)', category: 'Pronouns' },

  // Daily Verbs
  { id: 'v-021', word: 'Go', meaning: 'Pergi', category: 'Daily Verbs' },
  { id: 'v-022', word: 'Come', meaning: 'Datang', category: 'Daily Verbs' },
  { id: 'v-023', word: 'Eat', meaning: 'Makan', category: 'Daily Verbs' },
  { id: 'v-024', word: 'Drink', meaning: 'Minum', category: 'Daily Verbs' },
  { id: 'v-025', word: 'Sleep', meaning: 'Tidur', category: 'Daily Verbs' },
  { id: 'v-026', word: 'Wake up', meaning: 'Bangun tidur', category: 'Daily Verbs' },
  { id: 'v-027', word: 'Study', meaning: 'Belajar', category: 'Daily Verbs' },
  { id: 'v-028', word: 'Work', meaning: 'Bekerja', category: 'Daily Verbs' },
  { id: 'v-029', word: 'Play', meaning: 'Bermain', category: 'Daily Verbs' },
  { id: 'v-030', word: 'Read', meaning: 'Membaca', category: 'Daily Verbs' },
  { id: 'v-031', word: 'Write', meaning: 'Menulis', category: 'Daily Verbs' },
  { id: 'v-032', word: 'Listen', meaning: 'Mendengarkan', category: 'Daily Verbs' },
  { id: 'v-033', word: 'Speak', meaning: 'Berbicara', category: 'Daily Verbs' },
  { id: 'v-034', word: 'Walk', meaning: 'Berjalan', category: 'Daily Verbs' },
  { id: 'v-035', word: 'Run', meaning: 'Berlari', category: 'Daily Verbs' },
  { id: 'v-036', word: 'Drive', meaning: 'Mengemudi', category: 'Daily Verbs' },
  { id: 'v-037', word: 'Cook', meaning: 'Memasak', category: 'Daily Verbs' },
  { id: 'v-038', word: 'Clean', meaning: 'Membersihkan', category: 'Daily Verbs' },
  { id: 'v-039', word: 'Buy', meaning: 'Membeli', category: 'Daily Verbs' },
  { id: 'v-040', word: 'Sell', meaning: 'Menjual', category: 'Daily Verbs' },
  { id: 'v-041', word: 'Help', meaning: 'Membantu', category: 'Daily Verbs' },
  { id: 'v-042', word: 'Ask', meaning: 'Bertanya', category: 'Daily Verbs' },
  { id: 'v-043', word: 'Answer', meaning: 'Menjawab', category: 'Daily Verbs' },
  { id: 'v-044', word: 'Think', meaning: 'Berpikir', category: 'Daily Verbs' },
  { id: 'v-045', word: 'Know', meaning: 'Mengetahui', category: 'Daily Verbs' },
  { id: 'v-046', word: 'See', meaning: 'Melihat', category: 'Daily Verbs' },
  { id: 'v-047', word: 'Watch', meaning: 'Menonton', category: 'Daily Verbs' },
  { id: 'v-048', word: 'Look', meaning: 'Melihat / Tampak', category: 'Daily Verbs' },
  { id: 'v-049', word: 'Find', meaning: 'Menemukan', category: 'Daily Verbs' },
  { id: 'v-050', word: 'Give', meaning: 'Memberikan', category: 'Daily Verbs' },
  { id: 'v-051', word: 'Take', meaning: 'Mengambil', category: 'Daily Verbs' },
  { id: 'v-052', word: 'Make', meaning: 'Membuat', category: 'Daily Verbs' },
  { id: 'v-053', word: 'Open', meaning: 'Membuka', category: 'Daily Verbs' },
  { id: 'v-054', word: 'Close', meaning: 'Menutup', category: 'Daily Verbs' },
  { id: 'v-055', word: 'Start', meaning: 'Mulai', category: 'Daily Verbs' },
  { id: 'v-056', word: 'Stop', meaning: 'Berhenti', category: 'Daily Verbs' },
  { id: 'v-057', word: 'Try', meaning: 'Mencoba', category: 'Daily Verbs' },
  { id: 'v-058', word: 'Use', meaning: 'Menggunakan', category: 'Daily Verbs' },
  { id: 'v-059', word: 'Need', meaning: 'Membutuhkan', category: 'Daily Verbs' },
  { id: 'v-060', word: 'Want', meaning: 'Menginginkan', category: 'Daily Verbs' },

  // Adjectives
  { id: 'v-061', word: 'Good', meaning: 'Baik / Bagus', category: 'Adjectives' },
  { id: 'v-062', word: 'Bad', meaning: 'Buruk / Jelek', category: 'Adjectives' },
  { id: 'v-063', word: 'Big', meaning: 'Besar', category: 'Adjectives' },
  { id: 'v-064', word: 'Small', meaning: 'Kecil', category: 'Adjectives' },
  { id: 'v-065', word: 'Long', meaning: 'Panjang', category: 'Adjectives' },
  { id: 'v-066', word: 'Short', meaning: 'Pendek', category: 'Adjectives' },
  { id: 'v-067', word: 'Tall', meaning: 'Tinggi (orang)', category: 'Adjectives' },
  { id: 'v-068', word: 'Fast', meaning: 'Cepat', category: 'Adjectives' },
  { id: 'v-069', word: 'Slow', meaning: 'Lambat', category: 'Adjectives' },
  { id: 'v-070', word: 'Hot', meaning: 'Panas', category: 'Adjectives' },
  { id: 'v-071', word: 'Cold', meaning: 'Dingin', category: 'Adjectives' },
  { id: 'v-072', word: 'New', meaning: 'Baru', category: 'Adjectives' },
  { id: 'v-073', word: 'Old', meaning: 'Tua / Lama', category: 'Adjectives' },
  { id: 'v-074', word: 'Happy', meaning: 'Senang / Bahagia', category: 'Adjectives' },
  { id: 'v-075', word: 'Sad', meaning: 'Sedih', category: 'Adjectives' },
  { id: 'v-076', word: 'Beautiful', meaning: 'Cantik / Indah', category: 'Adjectives' },
  { id: 'v-077', word: 'Ugly', meaning: 'Jelek / Buruk rupa', category: 'Adjectives' },
  { id: 'v-078', word: 'Strong', meaning: 'Kuat', category: 'Adjectives' },
  { id: 'v-079', word: 'Weak', meaning: 'Lemah', category: 'Adjectives' },
  { id: 'v-080', word: 'Hard', meaning: 'Keras / Sulit', category: 'Adjectives' },
  { id: 'v-081', word: 'Easy', meaning: 'Mudah', category: 'Adjectives' },
  { id: 'v-082', word: 'Clean', meaning: 'Bersih', category: 'Adjectives' },
  { id: 'v-083', word: 'Dirty', meaning: 'Kotor', category: 'Adjectives' },
  { id: 'v-084', word: 'Rich', meaning: 'Kaya', category: 'Adjectives' },
  { id: 'v-085', word: 'Poor', meaning: 'Miskin', category: 'Adjectives' },
  { id: 'v-086', word: 'Expensive', meaning: 'Mahal', category: 'Adjectives' },
  { id: 'v-087', word: 'Cheap', meaning: 'Murah', category: 'Adjectives' },
  { id: 'v-088', word: 'Full', meaning: 'Penuh / Kenyang', category: 'Adjectives' },
  { id: 'v-089', word: 'Empty', meaning: 'Kosong', category: 'Adjectives' },
  { id: 'v-090', word: 'Heavy', meaning: 'Berat', category: 'Adjectives' },
  { id: 'v-091', word: 'Light', meaning: 'Ringan / Terang', category: 'Adjectives' },
  { id: 'v-092', word: 'Loud', meaning: 'Keras (suara)', category: 'Adjectives' },
  { id: 'v-093', word: 'Quiet', meaning: 'Tenang / Sunyi', category: 'Adjectives' },
  { id: 'v-094', word: 'Busy', meaning: 'Sibuk', category: 'Adjectives' },
  { id: 'v-095', word: 'Free', meaning: 'Bebas / Gratis', category: 'Adjectives' },

  // People
  { id: 'v-096', word: 'Man', meaning: 'Pria / Laki-laki', category: 'People' },
  { id: 'v-097', word: 'Woman', meaning: 'Wanita / Perempuan', category: 'People' },
  { id: 'v-098', word: 'Boy', meaning: 'Anak laki-laki', category: 'People' },
  { id: 'v-099', word: 'Girl', meaning: 'Anak perempuan', category: 'People' },
  { id: 'v-100', word: 'Child', meaning: 'Anak-anak', category: 'People' },
  { id: 'v-101', word: 'Baby', meaning: 'Bayi', category: 'People' },
  { id: 'v-102', word: 'Student', meaning: 'Pelajar / Siswa', category: 'People' },
  { id: 'v-103', word: 'Teacher', meaning: 'Guru', category: 'People' },
  { id: 'v-104', word: 'Friend', meaning: 'Teman', category: 'People' },
  { id: 'v-105', word: 'Stranger', meaning: 'Orang asing', category: 'People' },
  { id: 'v-106', word: 'Neighbor', meaning: 'Tetangga', category: 'People' },
  { id: 'v-107', word: 'Guest', meaning: 'Tamu', category: 'People' },
  { id: 'v-108', word: 'Customer', meaning: 'Pelanggan', category: 'People' },
  { id: 'v-109', word: 'Boss', meaning: 'Atasan / Bos', category: 'People' },
  { id: 'v-110', word: 'Employee', meaning: 'Karyawan', category: 'People' },

  // Places
  { id: 'v-111', word: 'School', meaning: 'Sekolah', category: 'Places' },
  { id: 'v-112', word: 'Hospital', meaning: 'Rumah sakit', category: 'Places' },
  { id: 'v-113', word: 'Market', meaning: 'Pasar', category: 'Places' },
  { id: 'v-114', word: 'Restaurant', meaning: 'Restoran', category: 'Places' },
  { id: 'v-115', word: 'Bank', meaning: 'Bank', category: 'Places' },
  { id: 'v-116', word: 'Office', meaning: 'Kantor', category: 'Places' },
  { id: 'v-117', word: 'Library', meaning: 'Perpustakaan', category: 'Places' },
  { id: 'v-118', word: 'Park', meaning: 'Taman', category: 'Places' },
  { id: 'v-119', word: 'Airport', meaning: 'Bandara', category: 'Places' },
  { id: 'v-120', word: 'Station', meaning: 'Stasiun', category: 'Places' },
  { id: 'v-121', word: 'Hotel', meaning: 'Hotel', category: 'Places' },
  { id: 'v-122', word: 'Mall', meaning: 'Pusat perbelanjaan', category: 'Places' },
  { id: 'v-123', word: 'Church', meaning: 'Gereja', category: 'Places' },
  { id: 'v-124', word: 'Mosque', meaning: 'Masjid', category: 'Places' },
  { id: 'v-125', word: 'Museum', meaning: 'Museum', category: 'Places' },

  // Objects
  { id: 'v-126', word: 'Book', meaning: 'Buku', category: 'Objects' },
  { id: 'v-127', word: 'Pen', meaning: 'Pena', category: 'Objects' },
  { id: 'v-128', word: 'Bag', meaning: 'Tas', category: 'Objects' },
  { id: 'v-129', word: 'Key', meaning: 'Kunci', category: 'Objects' },
  { id: 'v-130', word: 'Phone', meaning: 'Telepon / HP', category: 'Objects' },
  { id: 'v-131', word: 'Wallet', meaning: 'Dompet', category: 'Objects' },
  { id: 'v-132', word: 'Umbrella', meaning: 'Payung', category: 'Objects' },
  { id: 'v-133', word: 'Watch', meaning: 'Jam tangan', category: 'Objects' },
  { id: 'v-134', word: 'Mirror', meaning: 'Cermin', category: 'Objects' },
  { id: 'v-135', word: 'Bottle', meaning: 'Botol', category: 'Objects' },
  { id: 'v-136', word: 'Cup', meaning: 'Cangkir / Gelas', category: 'Objects' },
  { id: 'v-137', word: 'Plate', meaning: 'Piring', category: 'Objects' },
  { id: 'v-138', word: 'Knife', meaning: 'Pisau', category: 'Objects' },
  { id: 'v-139', word: 'Spoon', meaning: 'Sendok', category: 'Objects' },
  { id: 'v-140', word: 'Fork', meaning: 'Garpu', category: 'Objects' },

  // School
  { id: 'v-141', word: 'Pencil', meaning: 'Pensil', category: 'School' },
  { id: 'v-142', word: 'Eraser', meaning: 'Penghapus', category: 'School' },
  { id: 'v-143', word: 'Ruler', meaning: 'Penggaris', category: 'School' },
  { id: 'v-144', word: 'Notebook', meaning: 'Buku tulis', category: 'School' },
  { id: 'v-145', word: 'Blackboard', meaning: 'Papan tulis', category: 'School' },
  { id: 'v-146', word: 'Chalk', meaning: 'Kapur', category: 'School' },
  { id: 'v-147', word: 'Classroom', meaning: 'Ruang kelas', category: 'School' },
  { id: 'v-148', word: 'Homework', meaning: 'Pekerjaan rumah', category: 'School' },
  { id: 'v-149', word: 'Exam', meaning: 'Ujian', category: 'School' },
  { id: 'v-150', word: 'Grade', meaning: 'Nilai / Kelas', category: 'School' },
  { id: 'v-151', word: 'Lesson', meaning: 'Pelajaran', category: 'School' },
  { id: 'v-152', word: 'Subject', meaning: 'Mata pelajaran', category: 'School' },
  { id: 'v-153', word: 'Dictionary', meaning: 'Kamus', category: 'School' },
  { id: 'v-154', word: 'Calculator', meaning: 'Kalkulator', category: 'School' },
  { id: 'v-155', word: 'Scissors', meaning: 'Gunting', category: 'School' },

  // House
  { id: 'v-156', word: 'Door', meaning: 'Pintu', category: 'House' },
  { id: 'v-157', word: 'Window', meaning: 'Jendela', category: 'House' },
  { id: 'v-158', word: 'Roof', meaning: 'Atap', category: 'House' },
  { id: 'v-159', word: 'Floor', meaning: 'Lantai', category: 'House' },
  { id: 'v-160', word: 'Wall', meaning: 'Dinding', category: 'House' },
  { id: 'v-161', word: 'Room', meaning: 'Kamar / Ruangan', category: 'House' },
  { id: 'v-162', word: 'Kitchen', meaning: 'Dapur', category: 'House' },
  { id: 'v-163', word: 'Bathroom', meaning: 'Kamar mandi', category: 'House' },
  { id: 'v-164', word: 'Bedroom', meaning: 'Kamar tidur', category: 'House' },
  { id: 'v-165', word: 'Garden', meaning: 'Taman / Kebun', category: 'House' },
  { id: 'v-166', word: 'Stairs', meaning: 'Tangga', category: 'House' },
  { id: 'v-167', word: 'Garage', meaning: 'Garasi', category: 'House' },
  { id: 'v-168', word: 'Fence', meaning: 'Pagar', category: 'House' },
  { id: 'v-169', word: 'Gate', meaning: 'Gerbang', category: 'House' },
  { id: 'v-170', word: 'Ceiling', meaning: 'Langit-langit', category: 'House' },

  // Work
  { id: 'v-171', word: 'Meeting', meaning: 'Rapat / Pertemuan', category: 'Work' },
  { id: 'v-172', word: 'Deadline', meaning: 'Batas waktu', category: 'Work' },
  { id: 'v-173', word: 'Report', meaning: 'Laporan', category: 'Work' },
  { id: 'v-174', word: 'Project', meaning: 'Proyek', category: 'Work' },
  { id: 'v-175', word: 'Salary', meaning: 'Gaji', category: 'Work' },
  { id: 'v-176', word: 'Contract', meaning: 'Kontrak', category: 'Work' },
  { id: 'v-177', word: 'Interview', meaning: 'Wawancara', category: 'Work' },
  { id: 'v-178', word: 'Resume', meaning: 'Daftar riwayat hidup', category: 'Work' },
  { id: 'v-179', word: 'Promotion', meaning: 'Promosi / Kenaikan jabatan', category: 'Work' },
  { id: 'v-180', word: 'Training', meaning: 'Pelatihan', category: 'Work' },

  // Technology
  { id: 'v-181', word: 'Computer', meaning: 'Komputer', category: 'Technology' },
  { id: 'v-182', word: 'Laptop', meaning: 'Laptop', category: 'Technology' },
  { id: 'v-183', word: 'Tablet', meaning: 'Tablet', category: 'Technology' },
  { id: 'v-184', word: 'Internet', meaning: 'Internet', category: 'Technology' },
  { id: 'v-185', word: 'Email', meaning: 'Surat elektronik', category: 'Technology' },
  { id: 'v-186', word: 'Password', meaning: 'Kata sandi', category: 'Technology' },
  { id: 'v-187', word: 'Download', meaning: 'Unduh', category: 'Technology' },
  { id: 'v-188', word: 'Upload', meaning: 'Unggah', category: 'Technology' },
  { id: 'v-189', word: 'Website', meaning: 'Situs web', category: 'Technology' },
  { id: 'v-190', word: 'Application', meaning: 'Aplikasi', category: 'Technology' },
  { id: 'v-191', word: 'Screen', meaning: 'Layar', category: 'Technology' },
  { id: 'v-192', word: 'Keyboard', meaning: 'Papan ketik', category: 'Technology' },
  { id: 'v-193', word: 'Mouse', meaning: 'Tetikus / Mouse', category: 'Technology' },
  { id: 'v-194', word: 'Printer', meaning: 'Printer / Pencetak', category: 'Technology' },
  { id: 'v-195', word: 'Camera', meaning: 'Kamera', category: 'Technology' },

  // Transportation
  { id: 'v-196', word: 'Car', meaning: 'Mobil', category: 'Transportation' },
  { id: 'v-197', word: 'Bus', meaning: 'Bus', category: 'Transportation' },
  { id: 'v-198', word: 'Train', meaning: 'Kereta', category: 'Transportation' },
  { id: 'v-199', word: 'Plane', meaning: 'Pesawat', category: 'Transportation' },
  { id: 'v-200', word: 'Ship', meaning: 'Kapal', category: 'Transportation' },
  { id: 'v-201', word: 'Motorcycle', meaning: 'Motor', category: 'Transportation' },
  { id: 'v-202', word: 'Bicycle', meaning: 'Sepeda', category: 'Transportation' },
  { id: 'v-203', word: 'Taxi', meaning: 'Taksi', category: 'Transportation' },
  { id: 'v-204', word: 'Truck', meaning: 'Truk', category: 'Transportation' },
  { id: 'v-205', word: 'Boat', meaning: 'Perahu', category: 'Transportation' },

  // Food
  { id: 'v-206', word: 'Rice', meaning: 'Nasi / Beras', category: 'Food' },
  { id: 'v-207', word: 'Bread', meaning: 'Roti', category: 'Food' },
  { id: 'v-208', word: 'Egg', meaning: 'Telur', category: 'Food' },
  { id: 'v-209', word: 'Meat', meaning: 'Daging', category: 'Food' },
  { id: 'v-210', word: 'Fish', meaning: 'Ikan', category: 'Food' },
  { id: 'v-211', word: 'Vegetable', meaning: 'Sayuran', category: 'Food' },
  { id: 'v-212', word: 'Fruit', meaning: 'Buah', category: 'Food' },
  { id: 'v-213', word: 'Sugar', meaning: 'Gula', category: 'Food' },
  { id: 'v-214', word: 'Salt', meaning: 'Garam', category: 'Food' },
  { id: 'v-215', word: 'Oil', meaning: 'Minyak', category: 'Food' },

  // Nature
  { id: 'v-216', word: 'Tree', meaning: 'Pohon', category: 'Nature' },
  { id: 'v-217', word: 'Flower', meaning: 'Bunga', category: 'Nature' },
  { id: 'v-218', word: 'Grass', meaning: 'Rumput', category: 'Nature' },
  { id: 'v-219', word: 'River', meaning: 'Sungai', category: 'Nature' },
  { id: 'v-220', word: 'Mountain', meaning: 'Gunung', category: 'Nature' },
  { id: 'v-221', word: 'Sea', meaning: 'Laut', category: 'Nature' },
  { id: 'v-222', word: 'Forest', meaning: 'Hutan', category: 'Nature' },
  { id: 'v-223', word: 'Sky', meaning: 'Langit', category: 'Nature' },
  { id: 'v-224', word: 'Sun', meaning: 'Matahari', category: 'Nature' },
  { id: 'v-225', word: 'Moon', meaning: 'Bulan', category: 'Nature' },
  { id: 'v-226', word: 'Star', meaning: 'Bintang', category: 'Nature' },
  { id: 'v-227', word: 'Cloud', meaning: 'Awan', category: 'Nature' },
  { id: 'v-228', word: 'Rain', meaning: 'Hujan', category: 'Nature' },
  { id: 'v-229', word: 'Wind', meaning: 'Angin', category: 'Nature' },
  { id: 'v-230', word: 'Stone', meaning: 'Batu', category: 'Nature' },

  // Time
  { id: 'v-231', word: 'Morning', meaning: 'Pagi', category: 'Time' },
  { id: 'v-232', word: 'Afternoon', meaning: 'Siang / Sore', category: 'Time' },
  { id: 'v-233', word: 'Evening', meaning: 'Petang / Sore', category: 'Time' },
  { id: 'v-234', word: 'Night', meaning: 'Malam', category: 'Time' },
  { id: 'v-235', word: 'Today', meaning: 'Hari ini', category: 'Time' },
  { id: 'v-236', word: 'Yesterday', meaning: 'Kemarin', category: 'Time' },
  { id: 'v-237', word: 'Tomorrow', meaning: 'Besok', category: 'Time' },
  { id: 'v-238', word: 'Now', meaning: 'Sekarang', category: 'Time' },
  { id: 'v-239', word: 'Soon', meaning: 'Segera / Sebentar lagi', category: 'Time' },
  { id: 'v-240', word: 'Later', meaning: 'Nanti', category: 'Time' },
  { id: 'v-241', word: 'Always', meaning: 'Selalu', category: 'Time' },
  { id: 'v-242', word: 'Never', meaning: 'Tidak pernah', category: 'Time' },
  { id: 'v-243', word: 'Sometimes', meaning: 'Kadang-kadang', category: 'Time' },
  { id: 'v-244', word: 'Often', meaning: 'Sering', category: 'Time' },
  { id: 'v-245', word: 'Hour', meaning: 'Jam', category: 'Time' },
  { id: 'v-246', word: 'Minute', meaning: 'Menit', category: 'Time' },
  { id: 'v-247', word: 'Second', meaning: 'Detik', category: 'Time' },
  { id: 'v-248', word: 'Week', meaning: 'Minggu', category: 'Time' },
  { id: 'v-249', word: 'Month', meaning: 'Bulan', category: 'Time' },
  { id: 'v-250', word: 'Year', meaning: 'Tahun', category: 'Time' },

  // Days
  { id: 'v-251', word: 'Monday', meaning: 'Senin', category: 'Days' },
  { id: 'v-252', word: 'Tuesday', meaning: 'Selasa', category: 'Days' },
  { id: 'v-253', word: 'Wednesday', meaning: 'Rabu', category: 'Days' },
  { id: 'v-254', word: 'Thursday', meaning: 'Kamis', category: 'Days' },
  { id: 'v-255', word: 'Friday', meaning: 'Jumat', category: 'Days' },
  { id: 'v-256', word: 'Saturday', meaning: 'Sabtu', category: 'Days' },
  { id: 'v-257', word: 'Sunday', meaning: 'Minggu', category: 'Days' },
  { id: 'v-258', word: 'Weekend', meaning: 'Akhir pekan', category: 'Days' },
  { id: 'v-259', word: 'Weekday', meaning: 'Hari kerja', category: 'Days' },
  { id: 'v-260', word: 'Holiday', meaning: 'Hari libur', category: 'Days' },

  // Months
  { id: 'v-261', word: 'January', meaning: 'Januari', category: 'Months' },
  { id: 'v-262', word: 'February', meaning: 'Februari', category: 'Months' },
  { id: 'v-263', word: 'March', meaning: 'Maret', category: 'Months' },
  { id: 'v-264', word: 'April', meaning: 'April', category: 'Months' },
  { id: 'v-265', word: 'May', meaning: 'Mei', category: 'Months' },
  { id: 'v-266', word: 'June', meaning: 'Juni', category: 'Months' },
  { id: 'v-267', word: 'July', meaning: 'Juli', category: 'Months' },
  { id: 'v-268', word: 'August', meaning: 'Agustus', category: 'Months' },
  { id: 'v-269', word: 'September', meaning: 'September', category: 'Months' },
  { id: 'v-270', word: 'October', meaning: 'Oktober', category: 'Months' },
  { id: 'v-271', word: 'November', meaning: 'November', category: 'Months' },
  { id: 'v-272', word: 'December', meaning: 'Desember', category: 'Months' },

  // Numbers
  { id: 'v-273', word: 'One', meaning: 'Satu', category: 'Numbers' },
  { id: 'v-274', word: 'Two', meaning: 'Dua', category: 'Numbers' },
  { id: 'v-275', word: 'Three', meaning: 'Tiga', category: 'Numbers' },
  { id: 'v-276', word: 'Four', meaning: 'Empat', category: 'Numbers' },
  { id: 'v-277', word: 'Five', meaning: 'Lima', category: 'Numbers' },
  { id: 'v-278', word: 'Six', meaning: 'Enam', category: 'Numbers' },
  { id: 'v-279', word: 'Seven', meaning: 'Tujuh', category: 'Numbers' },
  { id: 'v-280', word: 'Eight', meaning: 'Delapan', category: 'Numbers' },
  { id: 'v-281', word: 'Nine', meaning: 'Sembilan', category: 'Numbers' },
  { id: 'v-282', word: 'Ten', meaning: 'Sepuluh', category: 'Numbers' },
  { id: 'v-283', word: 'Eleven', meaning: 'Sebelas', category: 'Numbers' },
  { id: 'v-284', word: 'Twelve', meaning: 'Dua belas', category: 'Numbers' },
  { id: 'v-285', word: 'Twenty', meaning: 'Dua puluh', category: 'Numbers' },
  { id: 'v-286', word: 'Thirty', meaning: 'Tiga puluh', category: 'Numbers' },
  { id: 'v-287', word: 'Hundred', meaning: 'Seratus', category: 'Numbers' },
  { id: 'v-288', word: 'Thousand', meaning: 'Seribu', category: 'Numbers' },
  { id: 'v-289', word: 'Million', meaning: 'Satu juta', category: 'Numbers' },
  { id: 'v-290', word: 'Zero', meaning: 'Nol', category: 'Numbers' },

  // Colors
  { id: 'v-291', word: 'Red', meaning: 'Merah', category: 'Colors' },
  { id: 'v-292', word: 'Blue', meaning: 'Biru', category: 'Colors' },
  { id: 'v-293', word: 'Green', meaning: 'Hijau', category: 'Colors' },
  { id: 'v-294', word: 'Yellow', meaning: 'Kuning', category: 'Colors' },
  { id: 'v-295', word: 'White', meaning: 'Putih', category: 'Colors' },
  { id: 'v-296', word: 'Black', meaning: 'Hitam', category: 'Colors' },
  { id: 'v-297', word: 'Orange', meaning: 'Oranye', category: 'Colors' },
  { id: 'v-298', word: 'Purple', meaning: 'Ungu', category: 'Colors' },
  { id: 'v-299', word: 'Pink', meaning: 'Merah muda / Pink', category: 'Colors' },
  { id: 'v-300', word: 'Brown', meaning: 'Cokelat', category: 'Colors' },
  { id: 'v-301', word: 'Grey', meaning: 'Abu-abu', category: 'Colors' },
  { id: 'v-302', word: 'Gold', meaning: 'Emas', category: 'Colors' },
  { id: 'v-303', word: 'Silver', meaning: 'Perak', category: 'Colors' },

  // Family
  { id: 'v-304', word: 'Father', meaning: 'Ayah', category: 'Family' },
  { id: 'v-305', word: 'Mother', meaning: 'Ibu', category: 'Family' },
  { id: 'v-306', word: 'Brother', meaning: 'Kakak/adik laki-laki', category: 'Family' },
  { id: 'v-307', word: 'Sister', meaning: 'Kakak/adik perempuan', category: 'Family' },
  { id: 'v-308', word: 'Grandfather', meaning: 'Kakek', category: 'Family' },
  { id: 'v-309', word: 'Grandmother', meaning: 'Nenek', category: 'Family' },
  { id: 'v-310', word: 'Uncle', meaning: 'Paman', category: 'Family' },
  { id: 'v-311', word: 'Aunt', meaning: 'Bibi', category: 'Family' },
  { id: 'v-312', word: 'Cousin', meaning: 'Sepupu', category: 'Family' },
  { id: 'v-313', word: 'Son', meaning: 'Anak laki-laki (kandung)', category: 'Family' },
  { id: 'v-314', word: 'Daughter', meaning: 'Anak perempuan (kandung)', category: 'Family' },
  { id: 'v-315', word: 'Husband', meaning: 'Suami', category: 'Family' },
  { id: 'v-316', word: 'Wife', meaning: 'Istri', category: 'Family' },
  { id: 'v-317', word: 'Parents', meaning: 'Orang tua', category: 'Family' },
  { id: 'v-318', word: 'Family', meaning: 'Keluarga', category: 'Family' },

  // Weather
  { id: 'v-319', word: 'Sunny', meaning: 'Cerah / Bersinar', category: 'Weather' },
  { id: 'v-320', word: 'Cloudy', meaning: 'Berawan', category: 'Weather' },
  { id: 'v-321', word: 'Rainy', meaning: 'Hujan / Berhujan', category: 'Weather' },
  { id: 'v-322', word: 'Windy', meaning: 'Berangin', category: 'Weather' },
  { id: 'v-323', word: 'Foggy', meaning: 'Berkabut', category: 'Weather' },
  { id: 'v-324', word: 'Storm', meaning: 'Badai', category: 'Weather' },
  { id: 'v-325', word: 'Thunder', meaning: 'Guntur / Petir', category: 'Weather' },
  { id: 'v-326', word: 'Snow', meaning: 'Salju', category: 'Weather' },
  { id: 'v-327', word: 'Flood', meaning: 'Banjir', category: 'Weather' },
  { id: 'v-328', word: 'Drought', meaning: 'Kemarau / Kekeringan', category: 'Weather' },

  // Animals
  { id: 'v-329', word: 'Dog', meaning: 'Anjing', category: 'Animals' },
  { id: 'v-330', word: 'Cat', meaning: 'Kucing', category: 'Animals' },
  { id: 'v-331', word: 'Bird', meaning: 'Burung', category: 'Animals' },
  { id: 'v-332', word: 'Cow', meaning: 'Sapi', category: 'Animals' },
  { id: 'v-333', word: 'Horse', meaning: 'Kuda', category: 'Animals' },
  { id: 'v-334', word: 'Chicken', meaning: 'Ayam', category: 'Animals' },
  { id: 'v-335', word: 'Duck', meaning: 'Bebek', category: 'Animals' },
  { id: 'v-336', word: 'Rabbit', meaning: 'Kelinci', category: 'Animals' },
  { id: 'v-337', word: 'Tiger', meaning: 'Harimau', category: 'Animals' },
  { id: 'v-338', word: 'Lion', meaning: 'Singa', category: 'Animals' },
  { id: 'v-339', word: 'Elephant', meaning: 'Gajah', category: 'Animals' },
  { id: 'v-340', word: 'Monkey', meaning: 'Monyet', category: 'Animals' },
  { id: 'v-341', word: 'Snake', meaning: 'Ular', category: 'Animals' },
  { id: 'v-342', word: 'Frog', meaning: 'Katak', category: 'Animals' },
  { id: 'v-343', word: 'Butterfly', meaning: 'Kupu-kupu', category: 'Animals' },
  { id: 'v-344', word: 'Bee', meaning: 'Lebah', category: 'Animals' },
  { id: 'v-345', word: 'Ant', meaning: 'Semut', category: 'Animals' },
  { id: 'v-346', word: 'Spider', meaning: 'Laba-laba', category: 'Animals' },
  { id: 'v-347', word: 'Crocodile', meaning: 'Buaya', category: 'Animals' },
  { id: 'v-348', word: 'Shark', meaning: 'Hiu', category: 'Animals' },

  // Food & Drinks
  { id: 'v-349', word: 'Water', meaning: 'Air', category: 'Food & Drinks' },
  { id: 'v-350', word: 'Milk', meaning: 'Susu', category: 'Food & Drinks' },
  { id: 'v-351', word: 'Coffee', meaning: 'Kopi', category: 'Food & Drinks' },
  { id: 'v-352', word: 'Tea', meaning: 'Teh', category: 'Food & Drinks' },
  { id: 'v-353', word: 'Juice', meaning: 'Jus', category: 'Food & Drinks' },
  { id: 'v-354', word: 'Soup', meaning: 'Sup', category: 'Food & Drinks' },
  { id: 'v-355', word: 'Cake', meaning: 'Kue', category: 'Food & Drinks' },
  { id: 'v-356', word: 'Cookie', meaning: 'Kue kering', category: 'Food & Drinks' },
  { id: 'v-357', word: 'Noodle', meaning: 'Mie', category: 'Food & Drinks' },
  { id: 'v-358', word: 'Chicken', meaning: 'Ayam (daging)', category: 'Food & Drinks' },
  { id: 'v-359', word: 'Beef', meaning: 'Daging sapi', category: 'Food & Drinks' },
  { id: 'v-360', word: 'Tofu', meaning: 'Tahu', category: 'Food & Drinks' },
  { id: 'v-361', word: 'Tempeh', meaning: 'Tempe', category: 'Food & Drinks' },
  { id: 'v-362', word: 'Banana', meaning: 'Pisang', category: 'Food & Drinks' },
  { id: 'v-363', word: 'Apple', meaning: 'Apel', category: 'Food & Drinks' },
  { id: 'v-364', word: 'Mango', meaning: 'Mangga', category: 'Food & Drinks' },
  { id: 'v-365', word: 'Orange', meaning: 'Jeruk', category: 'Food & Drinks' },
  { id: 'v-366', word: 'Pineapple', meaning: 'Nanas', category: 'Food & Drinks' },
  { id: 'v-367', word: 'Coconut', meaning: 'Kelapa', category: 'Food & Drinks' },
  { id: 'v-368', word: 'Strawberry', meaning: 'Stroberi', category: 'Food & Drinks' },

  // Question Words
  { id: 'v-369', word: 'What', meaning: 'Apa', category: 'Question Words' },
  { id: 'v-370', word: 'Who', meaning: 'Siapa', category: 'Question Words' },
  { id: 'v-371', word: 'Where', meaning: 'Di mana', category: 'Question Words' },
  { id: 'v-372', word: 'When', meaning: 'Kapan', category: 'Question Words' },
  { id: 'v-373', word: 'Why', meaning: 'Mengapa', category: 'Question Words' },
  { id: 'v-374', word: 'How', meaning: 'Bagaimana', category: 'Question Words' },
  { id: 'v-375', word: 'Which', meaning: 'Yang mana', category: 'Question Words' },
  { id: 'v-376', word: 'How much', meaning: 'Berapa (tidak terhitung)', category: 'Question Words' },
  { id: 'v-377', word: 'How many', meaning: 'Berapa banyak (terhitung)', category: 'Question Words' },
  { id: 'v-378', word: 'How long', meaning: 'Berapa lama', category: 'Question Words' },
  { id: 'v-379', word: 'How often', meaning: 'Seberapa sering', category: 'Question Words' },

  // Conjunctions
  { id: 'v-380', word: 'And', meaning: 'Dan', category: 'Conjunctions' },
  { id: 'v-381', word: 'Or', meaning: 'Atau', category: 'Conjunctions' },
  { id: 'v-382', word: 'But', meaning: 'Tetapi / Tapi', category: 'Conjunctions' },
  { id: 'v-383', word: 'Because', meaning: 'Karena', category: 'Conjunctions' },
  { id: 'v-384', word: 'So', meaning: 'Jadi / Sehingga', category: 'Conjunctions' },
  { id: 'v-385', word: 'If', meaning: 'Jika / Kalau', category: 'Conjunctions' },
  { id: 'v-386', word: 'Although', meaning: 'Meskipun', category: 'Conjunctions' },
  { id: 'v-387', word: 'Before', meaning: 'Sebelum', category: 'Conjunctions' },
  { id: 'v-388', word: 'After', meaning: 'Setelah', category: 'Conjunctions' },
  { id: 'v-389', word: 'While', meaning: 'Sementara / Sambil', category: 'Conjunctions' },
  { id: 'v-390', word: 'In', meaning: 'Di dalam / Di', category: 'Conjunctions' },
  { id: 'v-391', word: 'On', meaning: 'Di atas / Pada', category: 'Conjunctions' },
  { id: 'v-392', word: 'At', meaning: 'Di / Pada (waktu/tempat)', category: 'Conjunctions' },
  { id: 'v-393', word: 'For', meaning: 'Untuk', category: 'Conjunctions' },
  { id: 'v-394', word: 'With', meaning: 'Dengan', category: 'Conjunctions' },
  { id: 'v-395', word: 'Without', meaning: 'Tanpa', category: 'Conjunctions' },
  { id: 'v-396', word: 'Between', meaning: 'Antara', category: 'Conjunctions' },
  { id: 'v-397', word: 'Among', meaning: 'Di antara (banyak)', category: 'Conjunctions' },
  { id: 'v-398', word: 'From', meaning: 'Dari', category: 'Conjunctions' },
  { id: 'v-399', word: 'To', meaning: 'Ke / Kepada', category: 'Conjunctions' },

  // Emotions
  { id: 'v-400', word: 'Angry', meaning: 'Marah', category: 'Emotions' },
  { id: 'v-401', word: 'Afraid', meaning: 'Takut', category: 'Emotions' },
  { id: 'v-402', word: 'Surprised', meaning: 'Terkejut', category: 'Emotions' },
  { id: 'v-403', word: 'Excited', meaning: 'Bersemangat / Antusias', category: 'Emotions' },
  { id: 'v-404', word: 'Bored', meaning: 'Bosan', category: 'Emotions' },
  { id: 'v-405', word: 'Tired', meaning: 'Lelah / Capek', category: 'Emotions' },
  { id: 'v-406', word: 'Nervous', meaning: 'Gugup', category: 'Emotions' },
  { id: 'v-407', word: 'Confused', meaning: 'Bingung', category: 'Emotions' },
  { id: 'v-408', word: 'Proud', meaning: 'Bangga', category: 'Emotions' },
  { id: 'v-409', word: 'Ashamed', meaning: 'Malu', category: 'Emotions' },
  { id: 'v-410', word: 'Lonely', meaning: 'Kesepian', category: 'Emotions' },
  { id: 'v-411', word: 'Jealous', meaning: 'Cemburu / Iri', category: 'Emotions' },
  { id: 'v-412', word: 'Grateful', meaning: 'Bersyukur', category: 'Emotions' },
  { id: 'v-413', word: 'Disappointed', meaning: 'Kecewa', category: 'Emotions' },
  { id: 'v-414', word: 'Hopeful', meaning: 'Penuh harapan', category: 'Emotions' },

  // Jobs
  { id: 'v-415', word: 'Doctor', meaning: 'Dokter', category: 'Jobs' },
  { id: 'v-416', word: 'Nurse', meaning: 'Perawat', category: 'Jobs' },
  { id: 'v-417', word: 'Engineer', meaning: 'Insinyur / Teknisi', category: 'Jobs' },
  { id: 'v-418', word: 'Lawyer', meaning: 'Pengacara', category: 'Jobs' },
  { id: 'v-419', word: 'Accountant', meaning: 'Akuntan', category: 'Jobs' },
  { id: 'v-420', word: 'Pilot', meaning: 'Pilot', category: 'Jobs' },
  { id: 'v-421', word: 'Farmer', meaning: 'Petani', category: 'Jobs' },
  { id: 'v-422', word: 'Soldier', meaning: 'Tentara', category: 'Jobs' },
  { id: 'v-423', word: 'Police', meaning: 'Polisi', category: 'Jobs' },
  { id: 'v-424', word: 'Chef', meaning: 'Koki / Juru masak', category: 'Jobs' },
  { id: 'v-425', word: 'Journalist', meaning: 'Jurnalis / Wartawan', category: 'Jobs' },
  { id: 'v-426', word: 'Programmer', meaning: 'Programmer', category: 'Jobs' },
  { id: 'v-427', word: 'Designer', meaning: 'Desainer', category: 'Jobs' },
  { id: 'v-428', word: 'Manager', meaning: 'Manajer', category: 'Jobs' },
  { id: 'v-429', word: 'Dentist', meaning: 'Dokter gigi', category: 'Jobs' },

  // Body
  { id: 'v-430', word: 'Head', meaning: 'Kepala', category: 'Body' },
  { id: 'v-431', word: 'Face', meaning: 'Wajah', category: 'Body' },
  { id: 'v-432', word: 'Eye', meaning: 'Mata', category: 'Body' },
  { id: 'v-433', word: 'Nose', meaning: 'Hidung', category: 'Body' },
  { id: 'v-434', word: 'Mouth', meaning: 'Mulut', category: 'Body' },
  { id: 'v-435', word: 'Ear', meaning: 'Telinga', category: 'Body' },
  { id: 'v-436', word: 'Hair', meaning: 'Rambut', category: 'Body' },
  { id: 'v-437', word: 'Neck', meaning: 'Leher', category: 'Body' },
  { id: 'v-438', word: 'Shoulder', meaning: 'Bahu', category: 'Body' },
  { id: 'v-439', word: 'Arm', meaning: 'Lengan', category: 'Body' },
  { id: 'v-440', word: 'Hand', meaning: 'Tangan', category: 'Body' },
  { id: 'v-441', word: 'Finger', meaning: 'Jari', category: 'Body' },
  { id: 'v-442', word: 'Chest', meaning: 'Dada', category: 'Body' },
  { id: 'v-443', word: 'Stomach', meaning: 'Perut', category: 'Body' },
  { id: 'v-444', word: 'Back', meaning: 'Punggung', category: 'Body' },
  { id: 'v-445', word: 'Leg', meaning: 'Kaki (tungkai)', category: 'Body' },
  { id: 'v-446', word: 'Knee', meaning: 'Lutut', category: 'Body' },
  { id: 'v-447', word: 'Foot', meaning: 'Kaki (telapak)', category: 'Body' },
  { id: 'v-448', word: 'Toe', meaning: 'Jari kaki', category: 'Body' },
  { id: 'v-449', word: 'Skin', meaning: 'Kulit', category: 'Body' },

  // Furniture
  { id: 'v-450', word: 'Table', meaning: 'Meja', category: 'Furniture' },
  { id: 'v-451', word: 'Chair', meaning: 'Kursi', category: 'Furniture' },
  { id: 'v-452', word: 'Bed', meaning: 'Tempat tidur', category: 'Furniture' },
  { id: 'v-453', word: 'Sofa', meaning: 'Sofa', category: 'Furniture' },
  { id: 'v-454', word: 'Wardrobe', meaning: 'Lemari pakaian', category: 'Furniture' },
  { id: 'v-455', word: 'Shelf', meaning: 'Rak', category: 'Furniture' },
  { id: 'v-456', word: 'Lamp', meaning: 'Lampu', category: 'Furniture' },
  { id: 'v-457', word: 'Curtain', meaning: 'Gorden', category: 'Furniture' },
  { id: 'v-458', word: 'Carpet', meaning: 'Karpet', category: 'Furniture' },
  { id: 'v-459', word: 'Pillow', meaning: 'Bantal', category: 'Furniture' },
  { id: 'v-460', word: 'Blanket', meaning: 'Selimut', category: 'Furniture' },
  { id: 'v-461', word: 'Refrigerator', meaning: 'Kulkas', category: 'Furniture' },
  { id: 'v-462', word: 'Stove', meaning: 'Kompor', category: 'Furniture' },
  { id: 'v-463', word: 'Fan', meaning: 'Kipas angin', category: 'Furniture' },
  { id: 'v-464', word: 'Television', meaning: 'Televisi', category: 'Furniture' },

  // Education
  { id: 'v-465', word: 'Knowledge', meaning: 'Pengetahuan', category: 'Education' },
  { id: 'v-466', word: 'Science', meaning: 'Ilmu pengetahuan / Sains', category: 'Education' },
  { id: 'v-467', word: 'Mathematics', meaning: 'Matematika', category: 'Education' },
  { id: 'v-468', word: 'History', meaning: 'Sejarah', category: 'Education' },
  { id: 'v-469', word: 'Geography', meaning: 'Geografi', category: 'Education' },
  { id: 'v-470', word: 'Language', meaning: 'Bahasa', category: 'Education' },
  { id: 'v-471', word: 'Certificate', meaning: 'Sertifikat', category: 'Education' },
  { id: 'v-472', word: 'University', meaning: 'Universitas', category: 'Education' },
  { id: 'v-473', word: 'Lecture', meaning: 'Kuliah / Ceramah', category: 'Education' },
  { id: 'v-474', word: 'Research', meaning: 'Penelitian', category: 'Education' },

  // Travel
  { id: 'v-475', word: 'Passport', meaning: 'Paspor', category: 'Travel' },
  { id: 'v-476', word: 'Ticket', meaning: 'Tiket', category: 'Travel' },
  { id: 'v-477', word: 'Luggage', meaning: 'Bagasi / Koper', category: 'Travel' },
  { id: 'v-478', word: 'Journey', meaning: 'Perjalanan', category: 'Travel' },
  { id: 'v-479', word: 'Destination', meaning: 'Tujuan', category: 'Travel' },
  { id: 'v-480', word: 'Map', meaning: 'Peta', category: 'Travel' },
  { id: 'v-481', word: 'Tour', meaning: 'Tur / Wisata', category: 'Travel' },
  { id: 'v-482', word: 'Guide', meaning: 'Pemandu', category: 'Travel' },
  { id: 'v-483', word: 'Visa', meaning: 'Visa', category: 'Travel' },
  { id: 'v-484', word: 'Souvenir', meaning: 'Oleh-oleh / Cinderamata', category: 'Travel' },

  // Shopping
  { id: 'v-485', word: 'Price', meaning: 'Harga', category: 'Shopping' },
  { id: 'v-486', word: 'Discount', meaning: 'Diskon', category: 'Shopping' },
  { id: 'v-487', word: 'Receipt', meaning: 'Kwitansi / Struk', category: 'Shopping' },
  { id: 'v-488', word: 'Cash', meaning: 'Uang tunai', category: 'Shopping' },
  { id: 'v-489', word: 'Credit card', meaning: 'Kartu kredit', category: 'Shopping' },
  { id: 'v-490', word: 'Change', meaning: 'Kembalian', category: 'Shopping' },
  { id: 'v-491', word: 'Bill', meaning: 'Tagihan / Uang kertas', category: 'Shopping' },
  { id: 'v-492', word: 'Budget', meaning: 'Anggaran', category: 'Shopping' },
  { id: 'v-493', word: 'Profit', meaning: 'Keuntungan', category: 'Shopping' },
  { id: 'v-494', word: 'Loss', meaning: 'Kerugian', category: 'Shopping' },

  // Extra words to reach 500+
  { id: 'v-495', word: 'Love', meaning: 'Cinta / Suka', category: 'Emotions' },
  { id: 'v-496', word: 'Hate', meaning: 'Benci', category: 'Emotions' },
  { id: 'v-497', word: 'Trust', meaning: 'Kepercayaan', category: 'Emotions' },
  { id: 'v-498', word: 'Hope', meaning: 'Harapan', category: 'Emotions' },
  { id: 'v-499', word: 'Dream', meaning: 'Mimpi / Impian', category: 'Emotions' },
  { id: 'v-500', word: 'Courage', meaning: 'Keberanian', category: 'Emotions' },
  { id: 'v-501', word: 'Patience', meaning: 'Kesabaran', category: 'Emotions' },
  { id: 'v-502', word: 'Kindness', meaning: 'Kebaikan', category: 'Emotions' },
  { id: 'v-503', word: 'Wisdom', meaning: 'Kebijaksanaan', category: 'Emotions' },
  { id: 'v-504', word: 'Freedom', meaning: 'Kebebasan', category: 'Emotions' },
  { id: 'v-505', word: 'Peace', meaning: 'Kedamaian', category: 'Emotions' },
  { id: 'v-506', word: 'Justice', meaning: 'Keadilan', category: 'Emotions' },
  { id: 'v-507', word: 'Respect', meaning: 'Menghormati / Rasa hormat', category: 'Emotions' },
  { id: 'v-508', word: 'Responsibility', meaning: 'Tanggung jawab', category: 'Emotions' },
  { id: 'v-509', word: 'Friendship', meaning: 'Persahabatan', category: 'Emotions' },
  { id: 'v-510', word: 'Happiness', meaning: 'Kebahagiaan', category: 'Emotions' },
];

export const TOTAL_VOCAB = VOCABULARY.length;